version: '3.8'
services:
  mysql:
    container_name: e-unlock-mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: e-unlock
      MYSQL_USER: e-unlock-dev
      MYSQL_PASSWORD: e-unlock-dev
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
